FROM node:22-alpine AS build
WORKDIR /app
COPY apps/nestjs-api/package*.json ./
RUN npm ci
COPY apps/nestjs-api/ .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/main.js"]
